// Generated by CoffeeScript 1.10.0
(function() {
  var Engine, assert, should;

  should = require('should');

  assert = require('assert');

  Engine = require('../src/engine');

  describe('Engines', function() {
    var engine, facts, rules;
    rules = [
      {
        "id": 1,
        "condition": "R.when(this.transactionTotal > 500)",
        "consequence": "this.result = 1; R.stop()"
      }
    ];
    facts = {
      transactionTotal: 1000
    };
    engine = null;
    before(function() {
      return engine = new Engine(rules);
    });
    it('instantiates', function() {
      var i, len, ref, rule;
      engine.rules.should.be.ok;
      engine.R.should.be.ok;
      ref = engine.rules;
      for (i = 0, len = ref.length; i < len; i++) {
        rule = ref[i];
        rule.should.be.ok;
      }
    });
    return it('executes', function() {
      return engine.execute(facts, function(error, results) {
        results.should.be.ok;
        results.should.be.equal(1);
      });
    });
  });

}).call(this);

//# sourceMappingURL=test_engines.js.map
