// Generated by CoffeeScript 1.10.0
(function() {
  var assert, facts, should;

  should = require('should');

  assert = require('assert');

  facts = require('../controllers/facts');

  describe('Facts', function() {
    return it('todo', function() {});
  });

}).call(this);

//# sourceMappingURL=test_facts.js.map
