// Generated by CoffeeScript 1.10.0
(function() {
  var traverse;

  traverse = function(jsonObj, path, result) {
    var p, v;
    if (typeof jsonObj === "object") {
      for (p in jsonObj) {
        v = jsonObj[p];
        result.push({
          op: 'replace',
          path: path + "/" + p,
          value: v
        });
        traverse(v, path + "/" + p, result);
      }
    }
    return result;
  };

  module.exports = traverse;

}).call(this);

//# sourceMappingURL=traverse.js.map
