// Generated by CoffeeScript 1.10.0
(function() {
  var typeIsArray;

  typeIsArray = Array.isArray || function(value) {
    return {}.toString.call(value) === '[object Array]';
  };

  module.exports = typeIsArray;

}).call(this);

//# sourceMappingURL=typeIsArray.js.map
