// Generated by CoffeeScript 1.10.0
(function() {
  var Resource, mongoose;

  mongoose = require('mongoose');

  Resource = require('resourcejs');

  module.exports = function(app, model) {
    var resource;
    resource = Resource(app, '/rooms/:roomId', 'Layouts', model).rest({
      before: function(req, res, next) {
        req.body.room = req.params.roomId;
        req.modelQuery = this.model.where('room', req.params.roomId);
        return next();
      }
    }).patch({
      before: function(req, res, next) {
        var result, traverse;
        traverse = require('./helpers/traverse');
        if (!((req.body != null) && (req.body[0] != null) && (req.body[0].op != null))) {
          result = traverse(req.body[0], '', []);
          req.body[0] = result[0];
        }
        return next();
      }
    });
    resource.modelName = resource.modelName.substring(0, resource.modelName.length - 1);
    return resource;
  };

}).call(this);

//# sourceMappingURL=rooms_layouts.js.map
