// Generated by CoffeeScript 1.10.0
(function() {
  var R, RuleEngine, fact, rules;

  RuleEngine = require('node-rules');

  rules = [
    {
      "id": 1,
      "condition": function(R) {
        return R.when(this && (this.transactionTotal > 500));
      },
      "consequence": function(R) {
        this.result = false;
        return R.stop();
      }
    }
  ];

  fact = {
    "name": "user4",
    "application": "MOB2",
    "transactionTotal": 400,
    "cardType": "Credit Card"
  };

  R = new RuleEngine(rules, {
    ignoreFactChanges: true
  });

  R.execute(fact, function(result) {
    if (result.result) {
      return console.log("Payment Accepted");
    } else {
      return console.log("Payment Rejected");
    }
  });

}).call(this);

//# sourceMappingURL=rules_example.js.map
