// Generated by CoffeeScript 1.10.0
(function() {
  var Engine, RuleEngine;

  RuleEngine = require('node-rules');

  module.exports = Engine = (function() {
    function Engine(rules) {
      var i, len, rule;
      for (i = 0, len = rules.length; i < len; i++) {
        rule = rules[i];
        rule.condition = new Function('R', rule.condition);
        rule.consequence = new Function('R', rule.consequence);
      }
      this.rules = rules;
      this.R = new RuleEngine(this.rules);
    }

    Engine.prototype.execute = function(facts, callback) {
      return this.R.execute(facts, function(result) {
        if (result.result) {
          if (typeof result.result === "boolean") {
            callback(null, {});
          } else {
            callback(null, result.result);
          }
        } else {
          callback(null, {});
        }
      });
    };

    return Engine;

  })();

}).call(this);

//# sourceMappingURL=engine.js.map
