// Generated by CoffeeScript 1.10.0
(function() {
  var iEngine;

  module.exports = iEngine = (function() {
    function iEngine(rules) {
      throw new Error("Don't call super or not implemented");
    }

    iEngine.prototype.execute = function(facts, callback) {
      throw new Error("Not implemented");
    };

    return iEngine;

  })();

}).call(this);

//# sourceMappingURL=iEngine.js.map
