// Generated by CoffeeScript 1.10.0
(function() {
  var RulesPersistence;

  module.exports = RulesPersistence = (function() {
    function RulesPersistence() {
      this.rules = {};
      this.id = 0;
    }

    RulesPersistence.prototype.add = function(rules) {
      var i, len, results, rule;
      results = [];
      for (i = 0, len = rules.length; i < len; i++) {
        rule = rules[i];
        rule.condition = new Function('R', rule.condition);
        rule.consequence = new Function('R', rule.consequence);
        rule.id = this.id;
        results.push(this.rules[this.id++] = {
          rule: rule
        });
      }
      return results;
    };

    RulesPersistence.prototype.del = function(id) {
      return delete this.rules[id];
    };

    RulesPersistence.prototype.get = function(id) {
      var k, v;
      if (id == null) {
        id = null;
      }
      if ((id != null)) {
        return this.rules[id].rule;
      } else {
        return (function() {
          var ref, results;
          ref = this.rules;
          results = [];
          for (k in ref) {
            v = ref[k];
            results.push(v.rule);
          }
          return results;
        }).call(this);
      }
    };

    return RulesPersistence;

  })();

}).call(this);

//# sourceMappingURL=rulesPersistence.js.map
