// Generated by CoffeeScript 1.10.0
(function() {
  var ContextSchema, Mongoose, Schema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  ContextSchema = new Schema({
    name: String
  }, {
    strict: false
  });

  module.exports = {
    model: Mongoose.model("Context", ContextSchema),
    schema: ContextSchema
  };

}).call(this);

//# sourceMappingURL=context.js.map
