// Generated by CoffeeScript 1.10.0
(function() {
  var FactSchema, Mongoose, Schema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  FactSchema = new Schema({}, {
    strict: false
  });

  module.exports = {
    model: Mongoose.model("Fact", FactSchema),
    schema: FactSchema
  };

}).call(this);

//# sourceMappingURL=facts.js.mapp
