// Generated by CoffeeScript 1.10.0
(function() {
  var ContextSchema, FactSchema, Mongoose, RuleSchema, RulesSchema, Schema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  RuleSchema = new Schema({
    condition: String,
    consequence: String,
    priority: String
  });

  ContextSchema = new Schema({
    name: String,
    schema: String
  }, {
    strict: false
  });

  FactSchema = new Schema({
    name: String
  }, {
    strict: false
  });

  RulesSchema = new Schema({
    context: [ContextSchema],
    rules: [RuleSchema],
    factSchema: [FactSchema]
  });

  module.exports = {
    model: Mongoose.model("Rules", RulesSchema),
    schema: RulesSchema
  };

}).call(this);

//# sourceMappingURL=rule.js.map
